services:

  web:
    # interpolate from environment (set by workflow)
    # fallback to 'latest' if DOCKER_TAG is unset
    image: ${DOCKER_USER}/github-action:${DOCKER_TAG:-latest}
    ports:
      - "80:80"