name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    # Yahan tabdeel karein:
    runs-on: [self-hosted, prod] 
    
    env:
      DOCKER_USER: ${{ vars.DOCKER_USER }}
      
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Deploy with docker compose
          run: docker compose up -d --build