name: Deploy Flask App

on:
    # push:
    #     branches: [main]
    workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    env:
      DOCKER_USER: ${{ vars.DOCKER_USER }}
      # leave DOCKER_TAG unset so compose file defaults to 'latest'
      # set manually via workflow_dispatch inputs if you want a specific tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Deploy with docker compose
        run: |
          export DOCKER_TAG="${DOCKER_TAG:-latest}"

          docker compose down
          docker compose up -d --build --force-recreate --pull always
