name: docker Lint


on: 
    workflow_call:
    
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: hadolint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile